package dto

// Error codes
const (
	VALIDATION_ERROR    = "VALIDATION_ERROR"
	INTERNAL_ERROR      = "INTERNAL_ERROR"
	UNAUTHORIZED        = "UNAUTHORIZED"
	FORBIDDEN           = "FORBIDDEN"
	NOT_FOUND           = "NOT_FOUND"

	// Category
	CATEGORY_NOT_FOUND    = "CATEGORY_NOT_FOUND"
	CATEGORY_HAS_PRODUCTS = "CATEGORY_HAS_PRODUCTS"
	INVALID_CATEGORY      = "INVALID_CATEGORY"

	// Brand
	BRAND_NOT_FOUND    = "BRAND_NOT_FOUND"
	BRAND_HAS_PRODUCTS = "BRAND_HAS_PRODUCTS"

	// Product
	PRODUCT_NOT_FOUND      = "PRODUCT_NOT_FOUND"
	SLUG_EXISTS            = "SLUG_EXISTS"
	SKU_EXISTS             = "SKU_EXISTS"
	DISCOUNT_EXCEEDS_PRICE = "DISCOUNT_EXCEEDS_PRICE"

	// Product Image
	IMAGE_NOT_FOUND     = "IMAGE_NOT_FOUND"
	IMAGE_LIMIT_REACHED = "IMAGE_LIMIT_REACHED"
)
